---
# Configure these variables before running playbook.yml

hostname: "rpi_cam2"

# WIFI Config
wifi_ssid: ""
wifi_password: ""

# Gmail config
gmail_email: "<youremail>@gmail.com"
gmail_password: ""
mailname: "example.com"

# Alarm config
alarm_email_list: "example@example.com"

# Motion config
motion_live_user: "change_me"
motion_live_password: "change_me"
motion_live_port: 8080

# Dropbox config
dropbox_key: ""
dropbox_secret: "" 
dropbox_oauth_access_token: ""
dropbox_oauth_access_token_secret: ""

