#!/usr/bin/env ansible-playbook
---
- hosts: cams
  gather_facts: yes
  vars_files:
      - configure_me.yml
  vars:
     packages_to_install: [ screen mutt motion postfix ffmpegthumbnailer ]
     update_cache: yes
  sudo: yes
  tasks:
     - name: Update system
       apt:
          upgrade: yes
          update_cache: {{ update_cache }}
          cache_valid_time: 86400

     - name: install packages
       apt: pkg={{ item }} state=installed update_cache={{ update_cache }}
       with_items: packages_to_install

     - name: Setup camera
       path: /etc/modules
       block: bcm2835_v4l2

     - name: Check if camera device exists
       path: /dev/video0

     - name: Assign hostname
       raw:  "echo {{hostname|quote}} > /etc/hostname"

     - name: Assign mailname
       raw:  "echo {{mailname}} > /etc/mailname"

     - name: Setup WiFi
       path: /etc/wpa_supplicant/wpa_supplicant.conf
       insertafter: "update_config=1"
       block: |
           network={
               ssid="{{ wifi_ssid }}"
               psk="{{ wifi_password }}"
           }

     - name: Setup SASL Password
       path: /etc/postfix/sasl_passwd
       block: |
           [smtp.gmail.com]:587  {{ gmail_email }}:{{ gmail_password }}

     - name: Create SASL Database
       shell: postmap sasl_passwd
       args:
           chdir: /etc/postfix/
       
     - name: Setup postfix configuration
       path: /etc/postfix/main.cf
       block: |
           smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
           smtp_sasl_security_options = noanonymous
           smtp_sasl_auth_enable = yes
           smtp_tls_CAfile = /etc/postfix/cacert.pem
           smtp_use_tls = yes 
           myorigin = /etc/mailname
           relayhost = [smtp.gmail.com]:587

     - name: Create recording directory
       file: path=/home/pi/Dropbox/{{ hostname }} state=directory mode=0755

     - name: Setup fstab with tmpfs filesystems
       path: /etc/fstab
       block: |
           tmpfs    /tmp    tmpfs    defaults,noatime,nosuid,size=10m    0 0
           tmpfs    /var/tmp    tmpfs    defaults,noatime,nosuid,size=10m    0 0
           tmpfs    /var/log    tmpfs    defaults,noatime,nosuid,mode=0755,size=20m    0 0
           tmpfs    /home/pi/Dropbox/motion/{{ hostname }} tmpfs    defaults,noatime,nosuid,mode=0755,size=500m
       
     - name: Setup cronjobs


     - name: Configure motion
 
     - name: Add motion start script
       template: src=start.sh dest=/home/pi/start.sh

     - name: Add alarm script
       template: src=alarm.sh dest=/home/pi/alarm.sh

     - name: Add Dropbox uploader script 1
       template: src=dropbox_uploader.sh dest=/home/pi/dropbox_uploader.sh

     - name: Add Dropbox uploader script 2
       template: src=upload.sh dest=/home/pi/upload.sh

     - name: Add Dropbox uploader config
       template: src=dropbox.conf dest=/home/pi/.dropbox_uploader

     - cron:
         name: "Start motion on boot"
         special_time: reboot
         job: "/bin/bash /home/pi/motion/start.sh"

     - cron:
         name: "Verify that motion is started"
         minute: "*/1"
         job: "/bin/bash /home/pi/motion/start.sh"

     - cron:
         name: "Clear old alarm files"
         minute: "*/1"
         job: "find /home/pi/Dropbox/motion/{{ hostname }}/* -mtime +7 -exec rm {} \;"

     - name: Reboot
       shell: sleep 2 && shutdown -r now "Rebooting"
       async: 1
       poll: 0
       sudo: true
       ignore_errors: true

